version: '3'
services:
  node:
    container_name: ${NODE_CONTAINER_NAME}
    build:
      context: .
      args:
        - CONTAINER_PORT=${CONTAINER_PORT}
    ports:
     - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
     - .:/app
    env_file:
     - .env
    command: ["npm", "start"]
